version: '3.8'  

services:
  ecapa_tdnn:
    build: .
    volumes:
      - ./data:/usr/src/app/data
      - ./target:/usr/src/app/target
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    env_file:
      - ECAPA_TDNN.env

  my_tdnn:
    build: .
    volumes:
      - ./data:/usr/src/app/data
      - ./target:/usr/src/app/target
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    env_file:
      - .env
